// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: storagenode.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StorageNode_Put_FullMethodName         = "/dataplane.v1.StorageNode/Put"
	StorageNode_Get_FullMethodName         = "/dataplane.v1.StorageNode/Get"
	StorageNode_Del_FullMethodName         = "/dataplane.v1.StorageNode/Del"
	StorageNode_Ping_FullMethodName        = "/dataplane.v1.StorageNode/Ping"
	StorageNode_ClientWrite_FullMethodName = "/dataplane.v1.StorageNode/ClientWrite"
	StorageNode_Replicate_FullMethodName   = "/dataplane.v1.StorageNode/Replicate"
	StorageNode_Configure_FullMethodName   = "/dataplane.v1.StorageNode/Configure"
)

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageNodeClient interface {
	// Public API (client->gateway uses these)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelReply, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// Internal data-plane
	ClientWrite(ctx context.Context, in *ClientWriteRequest, opts ...grpc.CallOption) (*ClientWriteReply, error)
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateReply, error)
	// Control-plane lite
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureReply, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := c.cc.Invoke(ctx, StorageNode_Put_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, StorageNode_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelReply, error) {
	out := new(DelReply)
	err := c.cc.Invoke(ctx, StorageNode_Del_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, StorageNode_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) ClientWrite(ctx context.Context, in *ClientWriteRequest, opts ...grpc.CallOption) (*ClientWriteReply, error) {
	out := new(ClientWriteReply)
	err := c.cc.Invoke(ctx, StorageNode_ClientWrite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateReply, error) {
	out := new(ReplicateReply)
	err := c.cc.Invoke(ctx, StorageNode_Replicate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureReply, error) {
	out := new(ConfigureReply)
	err := c.cc.Invoke(ctx, StorageNode_Configure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
// All implementations must embed UnimplementedStorageNodeServer
// for forward compatibility
type StorageNodeServer interface {
	// Public API (client->gateway uses these)
	Put(context.Context, *PutRequest) (*PutReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	Del(context.Context, *DelRequest) (*DelReply, error)
	Ping(context.Context, *PingRequest) (*PingReply, error)
	// Internal data-plane
	ClientWrite(context.Context, *ClientWriteRequest) (*ClientWriteReply, error)
	Replicate(context.Context, *ReplicateRequest) (*ReplicateReply, error)
	// Control-plane lite
	Configure(context.Context, *ConfigureRequest) (*ConfigureReply, error)
	mustEmbedUnimplementedStorageNodeServer()
}

// UnimplementedStorageNodeServer must be embedded to have forward compatible implementations.
type UnimplementedStorageNodeServer struct {
}

func (UnimplementedStorageNodeServer) Put(context.Context, *PutRequest) (*PutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedStorageNodeServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStorageNodeServer) Del(context.Context, *DelRequest) (*DelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedStorageNodeServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStorageNodeServer) ClientWrite(context.Context, *ClientWriteRequest) (*ClientWriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientWrite not implemented")
}
func (UnimplementedStorageNodeServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedStorageNodeServer) Configure(context.Context, *ConfigureRequest) (*ConfigureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedStorageNodeServer) mustEmbedUnimplementedStorageNodeServer() {}

// UnsafeStorageNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServer will
// result in compilation errors.
type UnsafeStorageNodeServer interface {
	mustEmbedUnimplementedStorageNodeServer()
}

func RegisterStorageNodeServer(s grpc.ServiceRegistrar, srv StorageNodeServer) {
	s.RegisterService(&StorageNode_ServiceDesc, srv)
}

func _StorageNode_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_ClientWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).ClientWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_ClientWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).ClientWrite(ctx, req.(*ClientWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNode_ServiceDesc is the grpc.ServiceDesc for StorageNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.v1.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _StorageNode_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StorageNode_Get_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _StorageNode_Del_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StorageNode_Ping_Handler,
		},
		{
			MethodName: "ClientWrite",
			Handler:    _StorageNode_ClientWrite_Handler,
		},
		{
			MethodName: "Replicate",
			Handler:    _StorageNode_Replicate_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _StorageNode_Configure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storagenode.proto",
}
